### ISSUE TITLE
Column overflow in mobile

### ISSUE THREAD

**Issue by ghost** [pothula-bharat/Alpha#3]
Hi bharat your thought and aim is good that you are making your own framework i appreciate your work.
I tested your alpha so when coming to the mobile platform the content in every column is shrinking for that we need to zoom in to view the content so we will be facing the problem instead of shrinking the column make it one below the another so the content can be easily viewed in mobile device.

**Comment by pothula-bharat** [comment]
Hi, Ramu Yadav.. Thanks for informing about the issue. The issue has been resolved. 

Cheers,
